ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'admin';

CREATE TABLE TASKS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255)
);

CREATE TABLE USERS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255)
);

CREATE TABLE RESULTS (
  TaskID INT,
  UserID INT,
  Score INT,
  FOREIGN KEY (TaskID) REFERENCES TASKS(id),
  FOREIGN KEY (UserID) REFERENCES USERS(id)
);